### PR TITLE
Update runscript.sh

### PR DESCRIPTION
**Pull request by behzadh**
moved the jobId to the end of file's names + change the name of one folder

### CODE REVIEW

**Comment by behzadh** [comment]
Hi Alex, can you please accept my pull request? It is just some changes in the names of output files

**Comment by alexanderrichards** [comment]
sure I'm just helping Janusz, do you need it deployed as well

**Comment by behzadh** [comment]
yes, please. Do you think you can do it later today?

**Comment by alexanderrichards** [comment]
yes, give me like 5-10 mins

**Comment by alexanderrichards** [comment]
ok done

**Pull request merged**
